blog/urls.py
from django.contrib import admin
from django.urls import re_path,    reverse

from . import views, views_cbv
#현재 폴더에 있는 views를 임포트한다
app_name = 'blog'

urlpatterns = [
    re_path(r'^$', views_cbv.post_list, name='post_list'),
    re_path(r'(?P<id>\d+)/$', views_cbv.post_detail, name='post_detail'),
    re_path(r'^new/$', views.post_new, name='post_new'),
    re_path(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),
    re_path(r'^cbv/new/$', views_cbv.post_new),
    re_path(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    re_path(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
    re_path(r'^comments/$', views.comment_list, name='comment_list'),

]

piro_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import re_path, include
from django.conf import settings
urlpatterns = [
    re_path(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls')),
    re_path(r'^dojo/', include('dojo.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^shop/', include('shop.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import  debug_toolbar
    urlpatterns += [
        re_path(r'__debug__/', include(debug_toolbar.urls))
    ]

blog/models.py
# blog/models.py
import re
from django.conf import settings
from django.forms import ValidationError
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
from django.urls import reverse

def lnglat_validator(value):
    if not re.match(r'^(\d+\.?\d*),(\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdraw'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=True, related_name='blog_post_set')
    name = models.CharField(max_length=100, verbose_name='제목', help_text='제목을 입력해주세요. 최대 100자')
    content = models.TextField(verbose_name='내용')

    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                processors=[Thumbnail(300, 300)],
                                format='JPEG',
                                options={'quality': 60})

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50,
                              help_text='경도/위도 포맷으로 입력',
                              blank=True,
                              validators=[lnglat_validator]
                              )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=50)
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm
# Create your views here.

app_name = 'blog'

def post_list(request):

    qs = Post.objects.all().prefetch_related('tag_set', 'comment_set')
    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)
    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q': q,
    })

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)

    return render(request, 'blog/post_detail.html', {
        'post':post,
    })



def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            post.user = request.user
            post.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
        })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.user = request.user
            post.save()
            messages.success(request, '포스팅을 수정했습니다.')
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
        })

def comment_list(request):
    comment_list = Comment.objects.all().select_related('post')
    return render(request, 'blog/comment_list.html', {
        'comment_list': comment_list
    })

blog/templates/blog/comment_list.html
{% extends 'blog/layout.html' %}

{% block content %}
<ul>
{% for comment in comment_list %}
    <li>
        {{ comment }}
        {{ comment.post }}
    </li>
{% endfor %}
</ul>
{% endblock %}

blog/templates/blog/layout.html
{% extends 'layout.html' %}

{% block title %} AskDjango's Blog {% endblock %}

blog/templates/blog/post_confirm_delete.html
<h1>{{ post }} 삭제 확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">아니요. 취소!</a>
    <input type="submit" value="예 삭제하겠습니다."/>
</form>

blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %}
{% load imagekit %}

{% block title %}
    {{ post.name }}
{% endblock %}

            {% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>{{ post.name }}</h2>
            {% if post.photo %}
                <img src="{{ post.photo.url }}" alt="" class="img-fluid">
                {% thumbnail "100x100" post.photo %}

                {% thumbnail '200x200' post.photo as thumb %}
                <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt=""/>

                {% thumbnail "250x250" post.photo -- style="" onclick="" class="" %}
            {% endif %}
            {{ post.content |linebreaks}}
            <hr/>
            <h3>Comments</h3>
            {% for comment in post.comment_set.all %}
                <li>
                    {{ comment.message }}
                    <small> by {{ comment.author }}</small>
                    <small> at {{ comment.updated_at }}</small>
                </li>
            {% endfor %}
            <hr>
            <a class="btn-primary btn" href="{% url 'blog:post_list' %}">글 목록</a>
            <a class="btn-primary btn" href="{% url 'blog:post_edit' post.id %}" class="btn btn-primary">글 수정</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    <table>
        {% csrf_token %}
        {{ form }}
    </table>
    <input type="submit" value="제출"/>
</form>

blog/templates/blog/post_list.html
{% extends 'blog/layout.html' %}

{% block content %}
    <div class="container" style="margin-top: 25px;">
        <div class="jumbotron">
            <h1 class="display-4" style="font-weight: 500;">Django Template <sup>by AskDjango</sup></h1>
            <p>여러분의 파이썬/장고 페이스메이커가 되어드리겠습니다.</p>
            <a class="btn btn-primary" href="#" role="button">AskDjango 페이스북 그룹>></a>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="alert alert-info">
                    <li>http://localhost:8000/blog/ 주소로 접속해보세요</li>
                    <li>템플릿 경로를 blog/templates/post_list.html 경로가 아닌 blog/templates/blog/post_list.html 경로를 쓰는 지에 대한 이유는 후에 Template Loader에서 설명합니다.</li>
                </ul>
                <a href="{% url 'blog:post_new' %}" class="btn btn-primary float-right">New Post</a>
                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" class="btn btn-primary" value="검색"/>
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated at</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td>
                                    <a href="{% url 'blog:post_detail' post.id %}">{{ post.name }}</a>
                                    {% for tag in post.tag_set.all %}
                                        <span class="badge badge-secondary">{{ tag.name }}</span>
                                    {% endfor %}
                                </td>
                                <td><small>{{ post.author }}</small></td>
                                <td><small>{{ post.updated_at }}</small></td>
{#                                <td>#}
{#                                    {{ post.comment_set.all }}#}
{#                                </td>#}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}